name: Doxygen Deploy

on:
  push:
    branches:
      - main
      - teseo/doxy-deploy

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2.5.0

      - name: Update APT
        run: |
          sudo apt-get update

      - name: Install Dependencies
        run: |
          sudo apt-get -o Acquire::Retries=3 install \
          doxygen \
          graphviz

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Generate Doxygen Documentation
        run: doxygen docs/Doxyfile.in

      - name: Create .nojekyll
        run: touch docs/html/.nojekyll

      - name: Deploy ðŸš€
        uses: JamesIves/github-pages-deploy-action@v4.3.3
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: docs/html/ # The folder the action should deploy.
